# ROS interface settings
general:
  matches_msg_queue_size: 10
  matches_msg_name: tgt/matches
  image_msg_queue_size: 10
  image_msg_name: src/image

# viso2::Matcher params and tracker config
matcher:
  nms_n: 7
  nms_tau: 20
  match_binsize: 200
  match_radius: 400
  outlier_flow_tolerance: 4
  multi_stage: 1
  half_resolution: 0
  max_track_length: 100
  method: 0
  refinement: 1 #0: none, 1: pixel, 2: subpixel
